services:
  postgres:
    image: postgres:16
    container_name: fitme_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitme_net

volumes:
  postgres_data:

networks:
  fitme_net: